project:
  type: website
  output-dir: docs
website:
  title: "Portfolio"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
    right:
      - icon: github
        href: https://github.com/scipima
      - icon: linkedin
        href: https://www.linkedin.com/in/marco-scipioni-a10b2b8b/
      - icon: googlescholar
        href: https://scholar.google.com/citations?user=WuJGLH0AAAAJ&hl=en
format:
  html:
    theme: united
    css: styles.css



